### ISSUE TITLE
Add Email Information to Grading Tables

### ISSUE THREAD

**Issue by tmccormack165** [EzerIT/BibleOL#12]
When a teacher logs on to grade an exam they follow this procedure.
```
1. Log onto an administrative account
2. Go to My Data >> Grade Exams (or Grade Exercises)
3. Select Class
4. Select Exam
```

They are then viewing a grading table like this one:
<img width="937" alt="Screenshot 2023-10-03 at 9 31 17 PM" src="https://github.com/EzerIT/BibleOL/assets/60988784/09ebacc7-8abc-454a-ab79-2ddba85d91a6">

The objective of this issue is to add the student's email as a column in the grading table. This is important because it will make it easier to connect grading system on Bible Online Learner with an institution's  grading system.

**Comment by tmccormack165** [comment]
<img width="1168" alt="Screenshot 2023-10-17 at 12 58 08 PM" src="https://github.com/EzerIT/BibleOL/assets/60988784/bcdab28a-127d-4507-87f2-6bcc08207512">

**Comment by oliverglanz** [comment]
Beautiful. THis looks great, Timothy. Thanks for the good work!

**Comment by tmccormack165** [comment]
The Email information should now be viewable in the exam grading table on learner.bible
