### ISSUE TITLE
Investigate the Feasibility of Creating a Docker Container For Bible Online Learner

### ISSUE THREAD

**Issue by tmccormack165** [EzerIT/BibleOL#13]
The purpose of this objective is to improve the efficiency of the installation of Bible Online Learner. Docker separates applications from a machine's infrastructure, which makes installation more reproducible across operating systems. Before investing time into the development of a Bible Online Learner docker container, it is worthwhile to research the feasibility of this task.

**Comment by tmccormack165** [comment]
Ulrik has made a brilliant multicontainer appliction running Emdros and Bible Online Learner in https://github.com/emg/BibleOL/tree/master/Dockerfiles

**Comment by tmccormack165** [comment]
<img width="670" alt="Screenshot 2023-11-26 at 2 55 13 PM" src="https://github.com/EzerIT/BibleOL/assets/60988784/928267ec-07ac-4ed8-b01a-e9fb1f6a88d0">
This error is being displayed when port mapping into the Bible Online Learner container from a local host.

**Comment by ernstboogert** [comment]
@tmccormack165 Is this issue solved now? I will test the new Docker solution soon!

**Comment by tmccormack165** [comment]
This issue is complete now. Please go to BibleOL/Dockerfiles for detailed instructions on how to run the Bible Online Learner container on any machine.
