### ISSUE TITLE
Remove yellow shaddow when editing exercise

### ISSUE THREAD

**Issue by ernstboogert** [EzerIT/BibleOL#24]
When editing an exercise, there are weird yellow shadows... These might be the result of a css theme used in the past. Please remove...

![image](https://github.com/EzerIT/BibleOL/assets/14231507/9b454a3b-e515-48fa-a81b-f3e0277ae9ee)

**Comment by ernstboogert** [comment]
Hi @tmccormack165, it happens to be the case also with the My View button; please see the screenshot below...

![image](https://github.com/EzerIT/BibleOL/assets/14231507/dd01853b-9151-40b0-9bba-36a615b8e9f8)

**Comment by dgurtner** [comment]
I would be happy to contribute a fix for this. It looks like a it's a background in /jquery-ui-1.13.2.custom/jquery-ui.min.css. Let me know how I can help. 
![Screen Shot 2023-12-21 at 9 44 33 PM](https://github.com/EzerIT/BibleOL/assets/441345/cd536a7a-3147-444f-a2fe-d23c69653d33)
![Screen Shot 2023-12-21 at 9 42 01 PM](https://github.com/EzerIT/BibleOL/assets/441345/164cd9db-13eb-4b61-86f2-a3cf4d14fdb3)

**Comment by tmccormack165** [comment]
Hi @dgurtner, thank you very much for your solution. Section 3.2.1 of techdoc/techdoc.pdf outlines how to fork the main BibleOL repository. From there, you can add your changes to your forked changes and then hit "Contribute" to make a Pull Request, when you do that please include me as a reviewer. Then, I will be happy to update our server on learner.bible with your solution if the edits are cohesive with the system. 

Sincerely,
Timothy

<img width="954" alt="Screenshot 2023-12-24 at 12 39 01 PM" src="https://github.com/EzerIT/BibleOL/assets/60988784/764eddc2-f923-42f9-88d8-0fbd1d2dd17b">

**Comment by tmccormack165** [comment]
Hi everyone, thanks to @dgurtner input, I believe we have a working solution now:

There are yellow shadows in two places on the system that need to be removed. 

The first occurrence is when an exercise is being created:
<img width="883" alt="Screenshot 2023-12-24 at 1 21 43 PM" src="https://github.com/EzerIT/BibleOL/assets/60988784/ddd28342-ab2e-45f4-9dc0-a0aee4c7d3e2">

The second occurrence is when a student is taking an exam or exercise and clicks on "My View":
<img width="809" alt="Screenshot 2023-12-24 at 1 25 47 PM" src="https://github.com/EzerIT/BibleOL/assets/60988784/97eec584-deb3-4932-9ada-f11a58b73d96">

To remove these shadows I changed the padding-right attribute of .ui-tabs in ol.css:401 and ol.css:405 from 5px to 0px:
```
.ui-tabs .ui-tabs-nav .ui-state-default {
  border: none;
  padding-right: 0px;
}
.ui-tabs .ui-tabs-nav .ui-state-active {
  border: none;
  padding-right: 0px;
}
```

The edit deletes the yellow shadows:

<img width="1242" alt="Screenshot 2023-12-24 at 1 29 23 PM" src="https://github.com/EzerIT/BibleOL/assets/60988784/e815f363-7ccb-4407-9ba3-79b185ce54c7">

<img width="564" alt="Screenshot 2023-12-24 at 1 28 39 PM" src="https://github.com/EzerIT/BibleOL/assets/60988784/73f862d3-8f47-4301-9137-77a0832a80d5">

Edits:
<img width="693" alt="Screenshot 2023-12-24 at 1 33 11 PM" src="https://github.com/EzerIT/BibleOL/assets/60988784/8ed5dd59-d6fd-431f-8b9c-d92c766746ae">

**Comment by dgurtner** [comment]
I like your solution and I'm glad I could help!
