### ISSUE TITLE
Find a place to store large Emdros files

### ISSUE THREAD

**Issue by oz1cz** [EzerIT/BibleOL#25]
The Emdros text databases themselves are not stored in GitHub because they are very large, and GitHub has a maximum file size on their free service. This means that the large files are stored in Claus' personal Dropbox repository, and a git hook retrieves files from there whenever needed. A better solution for that should be found. Claus has plenty of space in his Dropbox, but he is the only one who can manage it, which is unfortunate. (The largest of the files is ETCBC4 which takes up 195 MB.)

GitHub has a "Large File Storage" extension (https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-git-large-file-storage), but I believe that costs money (although I could be wrong). 

I'm filing this as a bug. It's not a bug in Bible OL, but its a bug in the logistics around how we handle the Bible OL files.

**Comment by tmccormack165** [comment]
Hi @oz1cz, thank you for bringing this to my attention. I will have a proposal solution ASAP, apparrently Git LFS is free up to 1 GB of storage.

**Comment by ernstboogert** [comment]
@oz1cz @tmccormack165 I would indeed recommend to use Git LFS if possible. But let's store them in a separate repo, not in BibleOL.

**Comment by tmccormack165** [comment]
Updated Dropbox Links in [LB_2024_01_01](https://github.com/EzerIT/BibleOL/tree/LB_2024_01_01). I think that this is better than using Git LFS because it prevents users from having an extra installation step. Also, installing Git LFS is not simple for certain Linux architectures
