### ISSUE TITLE
Clause feature "linkage" cannot be blocked from showing

### ISSUE THREAD

**Issue by oliverglanz** [EzerIT/BibleOL#28]
When creating a clause exercise one cannot choose "Don't show" for the feature "linkage". 
<img width="716" alt="image" src="https://github.com/EzerIT/BibleOL/assets/8409738/448fd4a1-c6ff-45da-8ee0-5273b6442be4">

The consequence is that some answers can be revealed when the "MyView" button is being used. The below screenshot shows the linkage information "Clause:Relative" while the student is supposed to provide the correct answer for the clause relation (which would be "relative")

<img width="762" alt="image" src="https://github.com/EzerIT/BibleOL/assets/8409738/e55e34b8-142e-4d70-b839-b59d40582708">

Solution: Adding all clause features to the exercise "Feature" list to allow for choosing "show" options.

**Comment by tmccormack165** [comment]
Thank you @oliverglanz, I will work on this. Thank you for the solution, I hope to have this implemented by tomorrow.

**Comment by tmccormack165** [comment]
Skipping conditions to add features to the feature table, but I do not see a feature called "Linkage":
<img width="508" alt="Screenshot 2023-12-21 at 9 42 56 AM" src="https://github.com/EzerIT/BibleOL/assets/60988784/a13333b6-0e81-4fc1-9600-4ab542607b0e">

**Comment by oliverglanz** [comment]
I think that is a feature that is not made accessible via the GUI. @oz1cz might have some more information on this.

**Comment by tmccormack165** [comment]
Hi @oliverglanz , does this problem pertain to exercises related to **Clauses**, or is it exclusively a problem with **Clause Atom** exercises, or both?

**Comment by oz1cz** [comment]
The "Linkage" feature is available in the GUI. If you make an exercise about, for example, _phrases_, you will be able to set "Don't show" for Linkage under "Clause". If, however, you make an exercise about _clauses_, for some reason the ability to set "Don't show" for linkage disappears. 

This appears to be a genuine bug. Unfortunately, I don't know what causes it. I can look into it if you want me to, but not this side of Christmas.

**Comment by tmccormack165** [comment]
Thank you @oz1cz, I am hoping to solve it today because I think it would be a great opportunity for me to solve a genuine problem on the client code, I know that _code_TYPE_text_ is the true feature in question and "Linkage" is the friendly name.

**Comment by oz1cz** [comment]
Yes, @tmccormack165, and the "TYPE" means that it requires special handling. The name of the feature is _code_ and its format is _text_. This is the only feaure of this sort, so it's kind of special. (See section 9.1.4 in the Technical Documentation.)

**Comment by tmccormack165** [comment]
Thank you @oz1cz 

In response to deleted:
"Thank you [@oz1cz](https://github.com/oz1cz), I am hoping to solve it today because I think it would be a great opportunity for me to solve a genuine problem on the client code, I know that code_TYPE_text is the true feature in question and "Linkage" is the friendly name."

**Comment by tmccormack165** [comment]
Is it possible that a GrammarFeature is automatically given true values for ignoreSelect, ignoreShow, and ignoreRequest?

<img width="996" alt="Screenshot 2023-12-22 at 12 07 48 PM" src="https://github.com/EzerIT/BibleOL/assets/60988784/059fc74d-0c42-47f2-a189-64687fb2ad23">

**Comment by oz1cz** [comment]
I don't think so. But if you call getFeatureSetting() with a feature like _code_TYPE_text_, it will return the feature setting for _code_.
You can check the implementation of getFeatureSetting() in ts/configuration.ts.

**Comment by tmccormack165** [comment]
Yes, thanks, but when I change the setting for _code_ I get valueType is undefined in the console. I am not sure what that is in reference to.
<img width="603" alt="Screenshot 2023-12-22 at 1 43 42 PM" src="https://github.com/EzerIT/BibleOL/assets/60988784/8d0b8d3f-9a02-4181-ae33-bdb0e835f2f9">

**Comment by oz1cz** [comment]
I'm not sure what's happening here, unfortunately. I would need to debug it myself.

However, I have a hunch that you're looking in the wrong direction. If you want to display a "Don't show" button, then ignoreSelect, ignoreShow, and ignoreRequest are not the items that govern that. You may want take a look at the ButtonAndLabel class in paneltemplquizfeatures.ts. This is the class that is responsible for creating the Show/Request/Don't care/Don't show/Multiple choice buttons in the quiz creation dialogue. 

Take a look at line 448 in paneltemplquizfeatures.ts. This is where a ButtonAndLabel object is created. I would look there to see why _code_TYPE_text_ does not cause a ButtonAndLabel object to be created.

But I could be wrong. Maybe I'm just sending you on a wild goose chase.

**Comment by tmccormack165** [comment]
**This solution only works for Clause Atom exercises**

**In reference to pull request: #30  **

I am able to add the Linkage feature to the feature panel:
<img width="535" alt="Screenshot 2023-12-23 at 12 04 25 PM" src="https://github.com/EzerIT/BibleOL/assets/60988784/319f6337-8633-4f7d-b16c-1599307f70cd">

This setting works when running an exercise:
<img width="643" alt="Screenshot 2023-12-23 at 12 05 27 PM" src="https://github.com/EzerIT/BibleOL/assets/60988784/37ced736-b5ff-4706-9deb-d72fb869523c">

My methodology:
1. I add a condition to push Linkage (code_TYPE_text) to the keylist of the feature panel in paneltemplquizfeatures.ts:
```
// Go through all features and identify the ones to include in the panel
for (let featName in getObjectSetting(otype).featuresetting) {
    // special case for "Linkage" feature
    if(featName === 'code_TYPE_text') { 
        keylist.push(featName);
        continue;  
    }
    
    // Ignore features marked to be ignored, unless they belong to a SentenceGrammar
    if (getFeatureSetting(otype, featName).ignoreShow
        && getFeatureSetting(otype, featName).ignoreRequest
        && (sg===null || !sg.containsFeature(featName)))
        continue;

    // Ignore features of type 'url'
    if (typeinfo.obj2feat[otype][featName]==='url')
        continue;

    // Ignore the genuine feature already presented as "visual"
    if (hasSurfaceFeature && featName===configuration.surfaceFeature)
        continue;
    keylist.push(featName);
}
```
2. I also include code_TYPE_text to the objectSettings of the database specification file ETCBC4.db.json:
```
"clause_atom": {
    "mayselect": true,
    "featuresetting": {
        "code": {
            "ignoreSelect": true,
            "ignoreShow": true,
            "ignoreRequest": true
        },
        "code_TYPE_text": {
            
        },  
        "dist": {
            "ignoreSelect": true,
            "ignoreShow": true,
            "ignoreRequest": true
        } ...
    }
}
```
3. I also edit the settings in paneltemplquizfeatures.ts to allow for making a 'Don't Show' button for Linkage:
```
// Loop through the relevant features and create radio buttons for each
for (let ix=0; ix<keylist.length; ++ix) {
    let featName : string = keylist[ix]; // Feture name
    if(featName === 'code_TYPE_text') {
        var canShow = false;
        var canRequest = false;
        var canDisplayGrammar = true;
    }
    else {
        var canShow = !getFeatureSetting(otype, featName).ignoreShow;
        var canRequest = !getFeatureSetting(otype, featName).ignoreRequest;
        var canDisplayGrammar = sg!==null && sg.containsFeature(featName);
    }
    let bal = new ButtonsAndLabel(getFeatureFriendlyName(otype, featName),                     // The localized name of the feature  
                                  featName,                                                    // The Emdros name of the feature     
                                  otype,                                                       // The Emdros object type             
                                  useSavedFeatures ? ptqf.getSelector(featName) : ButtonSelection.DONT_CARE, // Initially selected radio button
                                  ptqf.getHideFeatures(featName),                              // List of feature values to hide from student
                                  Boolean(getFeatureSetting(otype,featName).alternateshowrequestSql), // Can multiple choice be used?       
                                  canShow,                             // Can this be a display feature?     
                                  canRequest,                          // Can this be a request feature?     
                                  canDisplayGrammar);                  // Can this be a "don't show" feature?
    this.allBAL.push(bal);
    table.append(bal.getRow());
}
```
4. I run ```make``` to compile the javascript and update the database via the ugly .json file

**Comment by oz1cz** [comment]
This seems like a sensible way to solve the problem. Hard coding a feature into the TypeScript code is unfortunate, but since the alternative requires a considerable amount of reprogramming, I think this is the best way to do it.

I do, however, have two comments:

1) _Linkage_ (feature "code_TYPE_tex") is not the only feature with the problem. _Syntactic code_ (feature "code") has the same problem and should be treated together with code_TYPE_text. In fact, "code" and "code_TYPE_text" provide exactly the same information, but in numeric or textual format.

2) The code

`    if(featName === 'code_TYPE_text')`

should probably be changed to

`    if (configuration.databaseName === 'ETCBC4' && otype === 'clause_atom' &&`
`          (featName === 'code_TYPE_text' || featName === 'code'))`

to make sure the special handling is not triggered by another feature named "code" or "code_TYPE_text", possibly in another database.

Note: I have not tested this extended if-statement.

**Comment by tmccormack165** [comment]
Hi @oliverglanz , does this problem pertain to exercises related to Clauses, or is it exclusively a problem with Clause Atom exercises, or both?

**Comment by tmccormack165** [comment]
I have solved this issue by adding a method in the PanelForOneType class called addManualButton(). The solution is in this [commit](https://github.com/EzerIT/BibleOL/commit/7febfa6af8122657cbe9af9242568499d7420b27)

**addManualButton:**
```
private addManualButton(real_name:string, friendly_name:string, otype:string, useSavedFeatures:boolean, get_selector:number, get_hide_features:string[]): JQuery {
            
        let useDropDown = false;        // Can multiple choice be used?
        let canShow = false;            // Can this be a display feature?
        let canRequest = false;         // Can this be a request feature?
        let canDisplayGrammar = true;   // Can this be a "don't show" feature?

        let new_bal = new ButtonsAndLabel(friendly_name,
            real_name,
            otype,
            useSavedFeatures ? get_selector : ButtonSelection.DONT_CARE,
            get_hide_features,
            useDropDown, 
            canShow, 
            canRequest, 
            canDisplayGrammar);

        // Add the new button and label to allBAL
        this.allBAL.push(new_bal);
        return new_bal.getRow();
    }
```
The result of this addition is an easy framework for adding any feature to the feature panel regardless of Object Type:
<img width="557" alt="Screenshot 2024-01-07 at 1 07 07 AM" src="https://github.com/EzerIT/BibleOL/assets/60988784/6b2d29d3-cd61-464d-97fa-88a7d2d5048a">

The corresponding features are then greyed out in the Grammar Selection Box:
<img width="742" alt="Screenshot 2024-01-07 at 1 08 55 AM" src="https://github.com/EzerIT/BibleOL/assets/60988784/4838cb69-7faf-437c-b730-d91063f310ce">

**Comment by oliverglanz** [comment]
Thanks Timothy for having solved this!
