### ISSUE TITLE
ol.css must not be edited manually

### ISSUE THREAD

**Issue by oz1cz** [EzerIT/BibleOL#35]
In commit number 0aeb010eacc6925efded12a102fcd3d556fdb8d6, merged from 134bffdd83460e27b49ca02d6d3fe7ceb8ccaec4 (with comment "hide yellow shadow") two lines were modified in ol.css.

The file ol.css should _never_ be edited manually. Changes should be made to ol.less and then this file should be compiled (using the _make_ command), which will generate ol.css and ol_zh.css. As it is, ol.css and ol_zh.css now provide different behavior: If you switch the interface language to Chinese, the yellow shadow still exists.

**Comment by tmccormack165** [comment]
Thank you for catching that Claus, that is resolved now in #[0f3d519](https://github.com/EzerIT/BibleOL/commit/0f3d5198dfb2b4dacc67bbf1b469564b4831c18d).
