### ISSUE TITLE
Implement search bar in the user overview page

### ISSUE THREAD

**Issue by ernstboogert** [EzerIT/BibleOL#37]
Currently it takes too much time to find a student. Especially when we have many students in the system. We should implement a search bar that allowes us to search on username, first/last name or email.

**Comment by tmccormack165** [comment]
This enhancement is now added to the user overview page.

<img width="1287" alt="Screenshot 2024-02-15 at 3 33 25 PM" src="https://github.com/EzerIT/BibleOL/assets/60988784/59e001e1-0183-43ab-9510-8e69928509e1">

**Comment by oliverglanz** [comment]
Fantastic. Thnks for the good work!
