### ISSUE TITLE
docker container cannot be stoped and restarted

### ISSUE THREAD

**Issue by oliverglanz** [EzerIT/BibleOL#40]
Timothy created a very pleasant docker installation procedure making it development work so much easier. Great!
However, what I found out (on apple silicon) that one cannot restart the container with docker after one has stopped the container from running. The only way to start the container again is by deleting the container (make clean) and creating the container from scratch again (make). 
Since some developmental work is done over a period of days with the computer being shutdown once in a while, it would be important to resume ones work be being able to restart the container one has worked on.

**Comment by tmccormack165** [comment]
Hi Oliver, thank you for catching that. I will have a solution soon. I think that adding ```stop``` target in the Makefile is what we need.

**Comment by tmccormack165** [comment]
This bug is now fixed by adding 'stop' and 'start' targets in the Makefiles. No matter what architecture a user is on, they can now type 'make stop' to pause a container, and 'make start' to resume their container.

**Comment by oliverglanz** [comment]
Excellent. Thanks, Timothy!
