### ISSUE TITLE
grader rights

### ISSUE THREAD

**Issue by oliverglanz** [EzerIT/BibleOL#41]
It is fantastic that we are able to have a grader get added to a course. There is just one caveat: the grader needs to be an administrator and has, therefore, more rights than the facilitator. This will add a great risk to the reliability of BibleOL since a grader (typically a professor's grad assistant) can delete course, exercises, change dictionary entries, etc.
Solution: The grader should have facilitator rights, not admin rights.

**Comment by tmccormack165** [comment]
Hi Oliver, this makes sense to me I will update learner.bible with this change ASAP.

**Comment by tmccormack165** [comment]
Hi Oliver, I hope you are well, right now I am focusing on finishing the upload of the UBS 5th Revised Edition - Greek New Testament to the platform, but if there is an urgent need to add a user as a grader, I can do so quickly manually, but it will be a few days perhaps until I can implement this change on learner.bible. Thank you.

**Comment by oliverglanz** [comment]
@tmccormack165 I can wait until you have implemented it to the learner.bible. As we are in the middle of the semester my colleagues have accommodated to the situation and gave their own login information to their GAs. I have informed them about the new "grader" option. But they will implement this next semester.

**Comment by tmccormack165** [comment]
@oliverglanz This enhancement is completed and the changes are active on learner.bible. A grader no longer is required to be a system administrator. **The only requirement is that a grader needs to be enrolled in the class that they grade for.**

**Comment by oliverglanz** [comment]
Thanks, Timothy!
