### ISSUE TITLE
Improvements order exercises

### ISSUE THREAD

**Issue by ernstboogert** [EzerIT/BibleOL#44]
To improve the clearity of the order of exercise questions, I suggest to make the following improvement:
1. To turn the empty input fields into dropdown numbers with all possible numbers for ordering (so if you have 12 options to order, the dropdown should display 1...12).
2. To show a dropdown only in case the user has selected show/request
3. (optional) to adjust the possible selections in all drop downs dynamically based on the number of show/request features, while keeping the number that the user has already chosen

Finally, please get rid of the yellow theme colors and replace them by light gray and a little darker gray as used elsewhere on the platform.

**Comment by tmccormack165** [comment]
This feature is completed now:
<img width="1199" alt="Screenshot 2024-03-19 at 10 54 48 AM" src="https://github.com/EzerIT/BibleOL/assets/60988784/ab6eb438-1866-4eb9-a939-67c1750474e4">
