### ISSUE TITLE
Improve allignment issues

### ISSUE THREAD

**Issue by ernstboogert** [EzerIT/BibleOL#45]
![image](https://github.com/EzerIT/BibleOL/assets/14231507/e3b2ee07-bdcd-4fda-8aca-d8a36f947980)

Some allignment things that can be solved... (see image above)

**Comment by tmccormack165** [comment]
There are two corrections made to view_text_display.php. The first correction is to make the _Quiz Description_ align with the _Shortcut Keys_ panel. The second correction is to move the _My View_ panel over to the right to align with the _Exercise Panel_.

<img width="1346" alt="Screenshot 2024-02-29 at 1 14 29 PM" src="https://github.com/EzerIT/BibleOL/assets/60988784/a526a041-719a-4b93-bf93-276c7065089c">


There is another cosmetic improvement to the user searchbar. The Clear and Search buttons have been moved beneath the search bar and shifted to the right.

**Before:**
<img width="1025" alt="Screenshot 2024-02-29 at 1 20 32 PM" src="https://github.com/EzerIT/BibleOL/assets/60988784/ba3ba912-e568-4196-ab98-1dc9e5577eb8">

**After:**
<img width="1027" alt="Screenshot 2024-02-29 at 1 21 41 PM" src="https://github.com/EzerIT/BibleOL/assets/60988784/6ae73cb2-d305-4043-a474-89072913a11f">
