### ISSUE TITLE
Unenrollment Error

### ISSUE THREAD

**Issue by tmccormack165** [EzerIT/BibleOL#46]
At least one professor has experienced some of their students being unenrolled from their class. This bug occurred on February 27th.

**Comment by tmccormack165** [comment]
Is it possible that when a teacher goes to Administration >> Classes >> Assign user, they could add their students, but if ‘OK’ is not pressed at the bottom of the assign user page, then the data is not submitted to the server?

**Comment by tmccormack165** [comment]
(PASS) Test #1: Test on learner.bible

1.1 Create a new class called ‘Development-Class’
1.2 Create five new users development1 → development5 all with pwd23 as the password.
1.3 Assign the users to the class Development
1.4 Add development5 as a grader
1.5 Log in as each user and take the exam
1.6 Ensure that development5 can see all the grades
1.7 Ensure that no students are unenrolled

**Comment by ernstboogert** [comment]
@oliverglanz, I think we need more cases of this error. Timothy did quite some testing, but he couldn't replicate it. For now I close the issue. If you encounter the issue again, please reopen.
