### ISSUE TITLE
All text is pulled for an exercise

### ISSUE THREAD

**Issue by jloewenstein** [EzerIT/BibleOL#51]
I made 2 almost identical exercises:
Passages: Everything
Sentences:
[word NORETRIEVE frequency_rank<=150 AND gn IN (m) AND nu IN (sg) AND sp IN (subs) AND suffix_person IN (p1,p2,p3) AND suffix_gender IN (m,f) AND suffix_number IN (sg)]
Fetures: 
Text - show
Suffix person - request Limited
Suffix gender - request Limited

This one works perfect:
![image](https://github.com/EzerIT/BibleOL/assets/163320105/12acafd4-c617-49f6-975d-b2286fbf55d6)

the next one:
Passages: Everything
Sentences:
[word NORETRIEVE frequency_rank<=200 AND gn IN (m) AND nu IN (sg) AND sp IN (subs) AND suffix_person IN (p1,p2,p3) AND suffix_gender IN (m,f) AND suffix_number IN (sg,pl)]
Fetures: 
Text - show
Suffix person - request Limited
Suffix gender - request Limited
Suffix gender - request Limited		

this one is bringing up every single word:
![image](https://github.com/EzerIT/BibleOL/assets/163320105/60d10bc9-0741-455c-8e67-e362c3986380)

What did I miss?

**Comment by tmccormack165** [comment]
Hello @jloewenstein, I can investigate this problem, can you please tell me which database you were using to create this exercise, was it Hebrew (ETCBC4, OT) or Hebrew (ETCBC4, Transliterated, OT), thank you.

Sincerely,
Timothy

**Comment by jloewenstein** [comment]
Hebrew (ETCBC4, OT)
Also, I just tried creating it again from scratch - and it works, perfect. I don't know what I did...

**Comment by tmccormack165** [comment]
Hello @jloewenstein, I am glad to hear it works, and I will still work to find out what is going on, there is a degree of randomness involved when creating an exercise, there is currently an open issue to improve the shuffling algorithm here [https://github.com/EzerIT/BibleOL/issues/36](https://github.com/EzerIT/BibleOL/issues/36)

**Comment by ernstboogert** [comment]
> Hebrew (ETCBC4, OT)
> Also, I just tried creating it again from scratch - and it works, perfect. I don't know what I did...
> 

Did you make sure that the query for Sentence is identical to the query for Sentence Unit? I think that if you unselect the option to keep them the same that it will ask about every word, but I have to test that...

**Comment by ernstboogert** [comment]
Hi @jloewenstein, since your next try worked perfectly, I consider the issue completed. Please let us know if you need any more help.
