### ISSUE TITLE
Enrolling

### ISSUE THREAD

**Issue by jloewenstein** [EzerIT/BibleOL#54]
![image](https://github.com/EzerIT/BibleOL/assets/163320105/586c219d-c874-482a-8b23-95909fc2b637)
This is a great addition, but as it seems to function right now, I can enroll into any restricted folder with no restrictions or notification to the owner. Maybe it can be: 
Request to enroll
this notifies the instructor and until the instructor approves instead of the button a status line appears: "enrollment pending approval"

**Comment by tmccormack165** [comment]
Hi @jloewenstein, I agree that this feature would enhance the user experience, thank you.

**Comment by ernstboogert** [comment]
@jloewenstein Teachers can set a password needed to enroll and share the password with only those students they want in their class. Does that suffice?
