### ISSUE TITLE
Export reports

### ISSUE THREAD

**Issue by jloewenstein** [EzerIT/BibleOL#58]
Again, the access and visualization of performance data is great!
Would it be possible to add an option to export a report of that data?

**Comment by tmccormack165** [comment]
Hello @jloewenstein, I believe that this function is possible with the "CSV" and "EXCEL" buttons to the far right of the performance data table. Perhaps we should add an "Export" label to make these buttons clear.

<img width="1706" alt="Screenshot 2024-03-21 at 9 15 39 AM" src="https://github.com/EzerIT/BibleOL/assets/60988784/44d8797b-9184-4fb6-ab3f-8de8805af30a">

**Comment by jloewenstein** [comment]
I completely missed it (I was looking for it on the bottom:)! This is great. I think this is enough.
