### ISSUE TITLE
PHP error at the bottom of every text display

### ISSUE THREAD

**Issue by oz1cz** [EzerIT/BibleOL#78]
At the bottom of every text display, this error message is displayed:

![image](https://github.com/user-attachments/assets/d7f411c9-9932-4869-89d5-f98457a2c8a6)

**Comment by oz1cz** [comment]
It seems to be the result of code that should only be executed as part of an exercise, but is nevertheless included in connection with normal text display.

**Comment by tmccormack165** [comment]
@oz1cz This problem is solved now, thank you for pointing it out.

<img width="1102" alt="Screenshot 2024-10-20 at 10 08 29 PM" src="https://github.com/user-attachments/assets/0ffc3793-c175-4e30-90dc-b2dcd0069da6">
