### ISSUE TITLE
Disable browser autocomplete on answer fields

### ISSUE THREAD

**Issue by elliotclee** [EzerIT/BibleOL#8]
Hi,

I've been assigned the use of bibleol.3bmoodle.dk for a class, and ran across an issue I thought was worth fixing. I'm attaching a patch that turns off autocomplete on the text input for quiz questions. This is helpful for a couple of reasons:
1. It stops the autocomplete pop-up from interfering with the Down Arrow, Up Arrow, Page Down, and Page Up keyboard shortcuts.
2. It stops the autocomplete pop-up from reminding the student of the answer they gave the previous time they took the quiz. (This matters if multiple attempts are allowed on the quiz or if it is being used as a memorization tool rather than a bona-fide quiz.)

I don't have a running BibleOL deployment of my own, so I don't have a good way to test this, but the change is simple enough that it should be fairly obvious.

I have some other ideas for improvements but first want to see if there's anyone maintaining this... :-)

[no-autocomplete.patch.gz](https://github.com/EzerIT/BibleOL/files/11631982/no-autocomplete.patch.gz)

**Comment by oz1cz** [comment]
Thank you for that patch!

**Comment by oz1cz** [comment]
Fixed in branch DBI_2023_06_03.
