### ISSUE TITLE
exercise timer in conflict with exam timer

### ISSUE THREAD

**Issue by oliverglanz** [EzerIT/BibleOL#82]
At this moment exams cannot be give, since the exam timer is in conflict with the exercise timer. 

The exercise timer itself works great when just going an exercise. But the problem starts when the exercise is part of an exam: Regardless of whether the exercise timer is set to "unlimited" or any specific time it disables the exam timer. The consequence is that when the Exam timer is ending the exam still continues since the exercise cannot be stopped. Here is a video that demonstrates the problem: 

https://youtu.be/p1rmnidL3C8?si=5YqJNJ58P0kJ-lUz

**Comment by tmccormack165** [comment]
This issue has been resolved.
