### ISSUE TITLE
Missing localization information in exercise details

### ISSUE THREAD

**Issue by oz1cz** [EzerIT/BibleOL#9]
1. Create an exercise with a display feature such as "Danish" or "English" or some other gloss language.
2. Run the exercise.
3. Go to _My data > Grade my quizzes_ and select the exercise.
4. Under "Grades for exercise" click the hyperlink number in the "Grade column"

This will produce an error because the language ("Danish", "English" or whatever) is not localized.

![image](https://github.com/EzerIT/BibleOL/assets/3694506/b9b2cee7-984e-43bc-897b-588795c7d6e1)

**Comment by tmccormack165** [comment]
This issue has been solved in [Localization changes copied from learner.bible](https://github.com/EzerIT/BibleOL/commit/c9047b5941a0ab69c93e6cb9ee1eef00cc0d8f26)
